{{/*
This manifest results a secret being created which has the key information
needed for backing up and restoring the etcd database.
*/}}

{{- if and .Values.backup.enabled .Values.manifests.secret_backup_restore }}

{{- $envAll := . }}
{{- $userClass := "backup_restore" }}
{{- $secretName := index $envAll.Values.secrets.etcd $userClass }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  BACKUP_ENABLED: {{ $envAll.Values.backup.enabled | quote | b64enc }}
  BACKUP_BASE_PATH: {{ $envAll.Values.backup.host_backup_path | b64enc }}
  LOCAL_DAYS_TO_KEEP: {{ $envAll.Values.backup.no_backup_keep | quote | b64enc }}
  REMOTE_BACKUP_ENABLED: {{ $envAll.Values.backup.remote_backup.enabled | quote | b64enc }}
  REMOTE_BACKUP_CONTAINER: {{ $envAll.Values.backup.remote_backup.container_name | b64enc }}
  REMOTE_BACKUP_DAYS_TO_KEEP: {{ $envAll.Values.backup.remote_backup.days_to_keep | quote | b64enc }}
  REMOTE_BACKUP_STORAGE_POLICY: {{ $envAll.Values.backup.remote_backup.storage_policy | b64enc }}
...
{{- end }}
