---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-apiserver
  namespace: kube-system
  labels:
    application: kubernetes
    component: apiserver
    kubernetes-apiserver-service: enabled
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: kube-apiserver
      image: {{ config['Genesis:images.kubernetes.apiserver'] }}
      command:
        {%- for argument in config.bootstrap_apiserver_prefix() %}
        - "{{ argument }}"
        {%- endfor %}
{% include "genesis-apiserver.yaml" with context %}
        - --etcd-servers=https://localhost:2379
        - --secure-port=6443
      volumeMounts:
        - name: config
          mountPath: /etc/kubernetes/apiserver
          readOnly: true
  volumes:
    - name: config
      hostPath:
        path: /etc/genesis/apiserver
