---
apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-scheduler
  namespace: kube-system
  labels:
    tier: control-plane
    application: kubernetes
    component: kube-scheduler
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: {{ config['Genesis:images.kubernetes.scheduler'] }}
      command:
      - ./hyperkube
      - kube-scheduler
      - --leader-elect=true
      - --kubeconfig=/etc/kubernetes/scheduler/kubeconfig.yaml
      # TaintNodesByCondition feature is unconditionally enabled and the
      # corresponding --feature-gates flags have been removed in 1.18.x
      # See: https://kubernetes.io/docs/setup/release/notes/#urgent-upgrade-notes
      #- --feature-gates=TaintNodesByCondition=true
      - --v=5
      volumeMounts:
        - name: config
          mountPath: /etc/kubernetes/scheduler
  volumes:
    - name: config
      hostPath:
        path: /etc/genesis/scheduler
